[tool.pytest.ini_options]
filterwarnings = ["error","ignore::UserWarning"]

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
profile = "black"

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",
    "SA01",
    "ES01",
    "GL01",
    "SS05"
]
exclude = [
    '\.__init__$',  # exclude __init__ methods because they are in the class docstring
]

[tool.black]
line-length = 120

[tool.mypy]
python_version = 3.9
ignore_missing_imports = true